### ISSUE TITLE
NO TIMER STOP BUTTON!

### ISSUE THREAD

**Issue by narcode** [borrob/VisualTimer_OSX#1]
NO TIMER STOP BUTTON!

![7390-1_6645 noriega felipe ignacio_stoop ernestine](https://cloud.githubusercontent.com/assets/15698441/14077417/8ac5df58-f4eb-11e5-863b-b51049708590.JPG)

**Comment by borrob** [comment]
Stop button was already there, but not in the compiled binary. Uploaded a new binary (with a start and stop button). Fixed with commit 576c83f
